FROM python:latest

WORKDIR /tools/loader/

## Install uv on Ubuntu
# The installer requires curl (and certificates) to download the release archive
RUN apt-get update && apt-get install -y --no-install-recommends curl ca-certificates

# Download the latest uv installer
ADD https://astral.sh/uv/install.sh /uv-installer.sh

# Run the installer then remove it
RUN sh /uv-installer.sh && rm /uv-installer.sh

# Ensure the installed binary is on the `PATH`
ENV PATH="/root/.local/bin/:$PATH"

## Run python scripts with uv
# COPY requiremets into the container
COPY pyproject.toml /tools/loader/pyproject.toml
#COPY env.py /tools/loader/env.py
RUN uv sync

# Copy the source code into the container
#OPY src /tools/loader/src

#COPY ../../configs /tools/loader/configs

# CMD ["uv", "run", "python", "src/config.py"]

# Run the environment setup script with uv
CMD ["uv", "run", "python", "env.py"]