services:
    pylovo-generation:
        profiles: [ "pylovo"]
        build:
            context: .
            dockerfile: Dockerfile
        stdin_open: true # Enable stdin for interactive input
        tty: true # Allocate a pseudo-TTY
        env_file:
            - ../../.env # Use root .env file with database credentials
            - pylovo.env
        volumes:
            - ./configs:/app/configs
            - ./src/pylovo:/app/mnt/pylovo
            - ../../configs:/app/mnt/configs-infdb #:ro # for root *.yml configs
            - ../../src/infdb_package:/app/mnt/infdb_package #
        extra_hosts:
            - "host.docker.internal:host-gateway"
