image: python:3.10-slim 

variables:
  CODE_PATH: "./src" 
  # DOCKER_HOST: "tcp://docker:2375"
  # DOCKER_TLS_CERTDIR: ""

stages:
  - install
  - lint
  # - build

cache:
  paths:
    - .cache/pip

default:
  tags:
    - database

install_dependencies:
  stage: install
  script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install --upgrade pip
    - pip install -r requirements.txt
  artifacts:
    expire_in: 1 week
    paths:
      - venv

lint:
  stage: lint
  script:
    - source venv/bin/activate
    - flake8 $CODE_PATH


#test version
# build:
#   stage: build
#   image: docker:24.0.5
#   services:
#     - docker:24.0.5-dind
#   dependencies:
#     - install_dependencies
#     - lint
#   script:
#     - echo "Starting the application using Docker Compose..."
#     - docker build -t my-fastapi-app .

