include:
  - local: '.gitlab-ci-main.yml' # For main branch
  - local: '.gitlab-ci-develop.yml' # For develop branch

rules:
  - if: $CI_COMMIT_BRANCH == "main"
    include: '.gitlab-ci-main.yml'
  - if: $CI_COMMIT_BRANCH == "develop"
    include: '.gitlab-ci-develop.yml'

# default:
#   tags:
#     - your-runner-tag


