# .gitlab-ci.yml

# Global variables
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  UV_CACHE_DIR: "$CI_PROJECT_DIR/.cache/uv"

# Default tags for all jobs
default:
  image: ghcr.io/astral-sh/uv:python3.12-trixie-slim

  tags:
    - infdb-feature
    - docker
    - python


# Cache configuration
cache:
  paths:
    - .cache/pip
    - .cache/uv
    - .venv/

# Stages
stages:
  - setup
#  - test
  - lint
  - docs

# Setup job
setup:
  stage: setup
  script:
    - uv sync --group=test
  artifacts:
    paths:
      - .venv/
    expire_in: 1 hour

## Test job
#test:
#  stage: test
#  <<: *install_uv
#  dependencies:
#    - setup
#  script:
#    - source .venv/bin/activate
#    - uv pip install pytest pytest-cov
#    - pytest --cov=src --cov-report=xml --cov-report=html
#  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
#  artifacts:
#    reports:
#      coverage_report:
#        coverage_format: cobertura
#        path: coverage.xml
#    paths:
#      - htmlcov/
#    expire_in: 1 week

pre-commit-hook:
  stage: lint
  dependencies:
    - setup
  script:
    - apt-get update && apt-get install -y git
    - source .venv/bin/activate
    - pre-commit run --all-files
  allow_failure: true

# Linting job
lint:
  stage: lint
  dependencies:
    - setup
  script:
    - source .venv/bin/activate
    - ruff check .
    - ruff format --check .
  allow_failure: true

# Type checking
type-check:
  stage: lint
  dependencies:
    - setup
  script:
    - source .venv/bin/activate
    - mypy src
    - mypy tests
    - mypy services/infdb-api/fastapi
    - mypy services/infdb-api/postgrest
    - mypy services/infdb-api/pygeoapi
    - mypy tools/infdb-basedata
    #- mypy tools/infdb-import
    #- mypy tools/infdb-metadata
    #- mypy tools/buildings-to-street
    # - mypy tools/kwp
    - mypy tools/ro-heat
    - mypy tools/linear-heat-density
    #- mypy tools/sunpot

  allow_failure: true

# Security check
# Bandit:
#  - Low level issues should not block but can  .
 # - Some options only exist in CLI, thus not stored in pyprojct.toml
# B608: SQL strings in Python is used a lot, ideally should be refactored: https://bandit.readthedocs.io/en/latest/plugins/b608_hardcoded_sql_expressions.html

security:
  stage: lint
  dependencies:
    - setup
  script:
    - source .venv/bin/activate
    - bandit -r **/*.py --severity-level medium --exclude build --skip "B608"
    - safety scan
  allow_failure: true


pages:
  stage: docs
  dependencies:
    - setup
  script:
    - source .venv/bin/activate
    - mkdocs build -f docs/mkdocs/mkdocs.yml --site-dir ../../public
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - ~/.cache/ 
  artifacts:
    paths:
      - public