## this file could be run maybe automatically as we would like to update our database
## in case of data changes occur on the db
## so that should not include any code in the router.
version: "3.8"
services:
  impexp:
    image: 3dcitydb/impexp
    container_name: impexp
    network_mode: database #should be same network name with our database
    #env variables must be same with citydb config
    environment:
      CITYDB_TYPE: postgresql
      CITYDB_HOST: citydb
      CITYDB_PORT: 5432
      CITYDB_NAME: citydb
      CITYDB_USERNAME: citydb_user
      CITYDB_PASSWORD: citydb_password
    volumes:
      - "./:/data"
    # data/test.gml is just an example data we keep.
    # Please refer to following link to read for import modes:
    # https://3dcitydb-docs.readthedocs.io/en/latest/impexp/import.html
    # but this causes really long execution times. So we would need to start this run and then wait to complete.
    # if we do not want to delete all db and restart because we might need to delete the volume each time,
    command: ["import", "/data/test.gml", "--import-mode=delete"] 
