version: '3.8'

services:
  downloader:
    image: alpine:latest
    command: >
      sh -c "
        apk add --no-cache aria2 &&
        aria2c --continue=true --allow-overwrite=false --auto-file-renaming=false https://geodaten.bayern.de/odd/a/lod2/citygml/meta/metalink/09780139.meta4 -d /data
      "
    volumes:
      - ./data_import/data:/data
    networks:
      - database

  citydb-tool:
    image: 3dcitydb/citydb-tool
    environment:
      - CITYDB_HOST_DATA_IMPORT
      - CITYDB_DB        
      - CITYDB_USER
      - CITYDB_PASSWORD
      - CITYDB_PORT_DATA_IMPORT
    command: [
      "import", "citygml",
      "-H", "${CITYDB_HOST_DATA_IMPORT}",
      "-d", "${CITYDB_DB}",
      "-u", "${CITYDB_USER}",
      "-p", "${CITYDB_PASSWORD}",
      "-P", "${CITYDB_PORT_DATA_IMPORT}",
      "/data/*.gml"
    ]
    volumes:
      - ./data_import/data:/data
    networks:
      - database

networks:
  database:
    external: true
