version: '3.8'

services:
  ## to share the same image across other importer services
  ## or just run the image first and then use for all services.
  _myimage_build:
    image: importer-base-image
    command: ['echo', 'build completed']  # any linux command which directly terminates.
    build:
      context: .
      dockerfile: Dockerfile.data_import

  lod2:
    image: importer-base-image
    container_name: data-init-tables
    env_file: .env
    networks:
      - database_network:
    working_dir: /app
    command: >
      bash -c "
        python -m data_import.imp.imp_initial_tables
      "
  plz:
    image: importer-base-image
    container_name: data-plz-importer
    env_file: .env
    networks:
      - database_network:
    working_dir: /app
    command: >
      bash -c "
        python -m data_import.imp.imp_plz
      "
  census2022:
    image: importer-base-image
    container_name: data-census2022-importer
    env_file: .env
    networks:
      - database_network:
    working_dir: /app
    command: >
      bash -c "
        python -m data_import.imp.imp_census2022
      "
  bkg:
    image: importer-base-image
    container_name: data-bkg-importer
    env_file: .env
    networks:
      - database_network:
    working_dir: /app
    command: >
      bash -c "
        python -m data_import.imp.imp_bkg
      "
  basemap:
    image: importer-base-image
    container_name: data-basemap-importer
    env_file: .env
    networks:
      - database_network:
    working_dir: /app
    command: >
      bash -c "
        python -m data_import.imp.imp_basemap
      "

networks:
  database_network::
    external: true
