version: '3.8'

services:
  downloader:
    image: alpine:latest
    command: >
      sh -c "
        apk add --no-cache aria2 &&
        aria2c --continue=true --allow-overwrite=false --auto-file-renaming=false https://geodaten.bayern.de/odd/a/lod2/citygml/meta/metalink/09780139.meta4 -d /data
      "
    volumes:
      - gml-data:/data
    networks:
      - database

  citydb-tool:
    image: 3dcitydb/citydb-tool
    command: >
      import
      citygml
      -H citydb
      -d citydb
      -u citydb_user
      -p citydb_password
      -P 5432
      /data/*.gml
    volumes:
      - gml-data:/data
    networks:
      - database

volumes:
  gml-data:

networks:
  database:
    external: true
