version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: database-app
    ports:
      - "8000:8000"  # Map container port 8000 to host port 8000
    depends_on:
      timescaledb:
        condition: service_healthy
      citydb:
        condition: service_healthy
    networks:
      - networkName
    environment:
        # TimescaleDB Configuration
        # i cant use 127.0.0.1 in the container because it means local host!
      -  TIMESCALE_USER
      -  TIMESCALE_PASSWORD
      -  TIMESCALE_HOST=host.docker.internal
      -  TIMESCALE_PORT
      -  TIMESCALE_DB

        # CityDB Configuration
      -  CITYDB_USER
      -  CITYDB_PASSWORD
      -  CITYDB_HOST=host.docker.internal
      -  CITYDB_PORT
      -  CITYDB_DB

  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb
    environment:
      POSTGRES_DB: ${TIMESCALE_DB}
      POSTGRES_USER: ${TIMESCALE_USER}
      POSTGRES_PASSWORD: ${TIMESCALE_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U timescale_user -d timescaledb_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data
    networks:
      - networkName

  citydb:
    image: 3dcitydb/3dcitydb-pg:5.0.0
    container_name: citydb
    environment:
      POSTGRES_DB: ${CITYDB_DB}
      POSTGRES_USER: ${CITYDB_USER}
      POSTGRES_PASSWORD: ${CITYDB_PASSWORD}
      SRID: ${SRID}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${CITYDB_USER} -d ${CITYDB_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"
    volumes:
      - citydb_data:/var/lib/postgresql/data
    networks:
      - networkName

volumes:
  timescale_data:
  citydb_data:

networks:
  networkName:
   name: database