version: "3.8"

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb
    environment:
      POSTGRES_DB: timescaledb_db
      POSTGRES_USER: timescale_user
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data
    networks:
      - networkName

  citydb:
    image: 3dcitydb/3dcitydb-pg:latest
    container_name: citydb
    environment:
      POSTGRES_DB: citydb
      POSTGRES_USER: citydb_user        
      POSTGRES_PASSWORD: citydb_password
      SRID: 4326
    ports:
      - "5433:5432"
    volumes:
      - citydb_data:/var/lib/postgresql/data
    networks:
      - networkName

volumes:
  timescale_data:
  citydb_data:

networks:
  networkName:
   name: database