variables:
  CODE_PATH: "./src" 

stages:
  - install
  - lint

install_dependencies:
  stage: install
  image: python:3.12
  script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
  cache:
    paths:
      - .cache/pip
  artifacts:
    paths:
      - venv

lint:
  stage: lint
  image: python:3.12
  script:
    - source venv/bin/activate
    - flake8 $CODE_PATH
    - black --check $CODE_PATH
