services:
    setup:
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /app
        volumes:
            # - ./configs:/tools/processor/configs:ro # for processor configs
            # - ./src:/tools/processor/src:ro # for source code
            # - ./main.py:/tools/processor/main.py:ro # for main script
            # - ./processor.log:/tools/processor/processor.log # for log file
            # - ./sql:/tools/processor/sql:ro # for source code
            # Only for development, for production: uncomment above and comment below
            - .:/app
            # - ../../configs:/app/configs-infdb:ro # for infdb configs
            - ../../:/app/infdb-root # for source code
            - /app/.venv
