services:
    pgadmin:
        profiles:
            - admin
        image: dpage/pgadmin4
        # container_name: pgadmin
        restart: unless-stopped
        environment:
            PGADMIN_DEFAULT_EMAIL: ${SERVICES_PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${SERVICES_PGADMIN_DEFAULT_PASSWORD}
            PGADMIN_CONFIG_SERVER_MODE: "False"
            PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
            # Postgres connection details for dynamic config generation
            #POSTGRES_HOST: postgres
            #POSTGRES_PORT: 5432
            #POSTGRES_DB: ${SERVICES_POSTGRES_DB}
            #POSTGRES_USER: ${SERVICES_POSTGRES_USER}
            POSTGRES_PASSWORD: ${SERVICES_POSTGRES_PASSWORD}
        ports:
            - ${SERVICES_PGADMIN_EXPOSED_PORT}:80
        volumes:
            - ./servers.json:/pgadmin4/servers.json:ro
            #- infdb-pgadmin-data:/var/lib/pgadmin
        networks:
            - infdb_network

#volumes:
#    infdb-pgadmin-data:
#        name: ${BASE_NAME}-pgadmin-data