services:
    buildings-to-street:
        image: infdb/buildings-to-street:latest
        profiles: [ "buildings-to-street" ]
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ${CONFIG_INFDB_PATH}:/app/mnt/configs-infdb #:ro # for *.yml configs and generated files
            - ./configs:/app/configs #:ro # for configs
            - .:/app/ #:ro # for source code # for development only
            - ../../src/infdb_package:/app/mnt/infdb_package
            # - /app/.venv # Exclude .venv from volume mount # for development only
        extra_hosts:
            - "host.docker.internal:host-gateway"
        env_file:
            - ../../.env
            - .env
        depends_on:
            infdb-basedata-buildings:
                condition: service_completed_successfully
            # process-streets:
            #     condition: service_completed_successfully