services:
  citydb-tool:
    image: 3dcitydb/citydb-tool
    container_name: citydb-tool
    environment:
      POSTGRES_DB: ${CITYDB_DB}
      POSTGRES_USER: ${CITYDB_USER}
      POSTGRES_PASSWORD: ${CITYDB_PASSWORD}
      SRID: ${CITYDB_EPSG}
    ports:
      - ${CITYDB_EXPOSED_PORT}:5432
    volumes:
      - citydb_data:/var/lib/postgresql/data
    networks:
      - ${NETWORK_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${CITYDB_USER} -d ${CITYDB_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
