services:
  citydbv4:
    image: 3dcitydb/3dcitydb-pg:13-3.2-4.4.0
    container_name: citydbV4
    environment:
      POSTGRES_DB: ${CITYDB_DB}
      POSTGRES_USER: ${CITYDB_USER}
      POSTGRES_PASSWORD: ${CITYDB_PASSWORD}
      SRID: ${CITYDBV4_SRID}
    ports:
      - ${CITYDBV4_PORT}:5432
    volumes:
      - citydb_data_v4:/var/lib/postgresql/data
    networks:
      - ${NETWORK_EXTERNAL_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${CITYDB_USER} -d ${CITYDB_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5