services:
  loader:
    build:
      context: ..
      dockerfile: Dockerfile.loader
    container_name: loader
    networks:
      - database
    depends_on:
      citydb:
        condition: service_healthy