services:
  processor:
    build:
      context: ../..
      dockerfile: src/services/processor/Dockerfile
    container_name: processor
    networks:
      - infdb
    volumes:
      - ../../configs:/app/configs
      - ../../${LOADER_PATH_BASE}:/app/${LOADER_PATH_BASE}/
networks:
  infdb:
    external: true
    name: infdb_${BASE_NETWORK_NAME}