processor:
  hosts:
    citydb:
      user: "{services/citydb/user}"
      password: "{services/citydb/password}"
      db: "{services/citydb/db}"
      host: "{services/citydb/host}"  # localhost for local development
      port: "{services/citydb/exposed_port}"  # 5433 (exposed port) for local development
      epsg: "{services/citydb/epsg}"
    timescaledb:
      user: "{services/timescaledb/user}"
      password: "{services/timescaledb/password}"
      db: "{services/timescaledb/db}"
      host: "{services/timescaledb/host}"   # localhost for local development
      port: 5432
  path:
    base: "{base/path/base}/opendata"
    processed: "{base/path/base}/{base/name}"