loader:
  hosts:
    citydb:
      user: citydb_user #"{services/citydb/user}"
      password: citydb_password #"{services/citydb/password}"
      db: "{services/citydb/db}"
      host: "{services/citydb/host}"  # localhost for local development
      port: "{services/citydb/exposed_port}"  # 5433 (exposed port) for local development
      epsg: "{services/citydb/epsg}"
    timescaledb:
      user: "{services/timescaledb/user}"
      password: "{services/timescaledb/password}"
      db: "{services/timescaledb/db}"
      host: "{services/timescaledb/host}"   # localhost for local development
      port: 5432
  path:
    base: "{base/path/base}/opendata"
    processed: "{base/path/base}/{base/name}"
  sources:
    zensus_2022:
      status: active
      resolutions:
        - 10km
        - 1km
        - 100m
      path:
        base: "{loader/path/base}/zensus_2022/"
        zip: "{loader/sources/zensus_2022/path/base}/zip/"
        unzip: "{loader/sources/zensus_2022/path/base}/unzip/"
        processed: "{loader/path/processed}/zensus_2022/"
      url: "https://www.zensus2022.de/DE/Ergebnisse-des-Zensus/_inhalt.html"
      schema: opendata
      prefix: cns22
      layer:
        - Zensus2022_Religion-Gitter.csv
        - Wohnungen_nach_Zahl_der_Raeume-Gitter.csv
        - Typ_der_Kernfamilie_nach_Kindern-Gitter.csv
        - Zensus2022_Anteil_Auslaender-Gitter.csv
        - Zensus2022_Durchschnittsalter-Gitter.csv
        - Durchschnittliche_Nettokaltmiete_und_Anzahl_der_Wohnungen-Gitter.csv
        - Zensus2022_Durchschn_Haushaltsgroesse-Gitter.csv
        - Zensus2022_Auslaenderanteil_ab18-Gitter.csv
        - Zensus2022_Bevoelkerungszahl-Gitter.csv
        - Zensus2022_Flaeche_der_Wohnung_10m2_Intervalle-Gitter.csv
        - Zensus2022_Durchschn_Flaeche_je_Bewohner-Gitter.csv
        - Zensus2022_Staatsangehoerigkeit_Gruppen-Gitter.csv
        - Zensus2022_Alter_in_10er-Jahresgruppen-Gitter.csv
        - Zensus2022_Durchschn_Flaeche_je_Wohnung-Gitter.csv
        - Zensus2022_Alter_5Altersklassen-Gitter.csv
        - Zensus2022_Zahl_der_Staatsangehoerigkeiten-Gitter.csv
        - Zensus2022_Eigentuemerquote-Gitter.csv
        - Zensus2022_Gebaeude_nach_Baujahr_in_Mikrozensus_Klassen-Gitter.csv
        - Zensus2022_Wohnung_Gebaeudetyp_Groesse-Gitter.csv
        - Zensus2022_Seniorenstatus_eines_privaten_Haushalts-Gitter.csv
        - Zensus2022_Familienstand-Gitter.csv
        - Zensus2022_Geburtsland_Gruppen-Gitter.csv
        - Zensus2022_Anteil_ueber_65-Gitter.csv
        - Zensus2022_Heizungsart-Gitter.csv # UTF-8 encoding issue
        - Zensus2022_Anteil_unter_18-Gitter.csv
        - Zensus2022_Marktaktive_Leerstandsquote-Gitter.csv
        - Zensus2022_Gebaeude_mit_Wohnraum_nach_Anzahl_der_Wohnungen_im_Gebaeude-Gitter.csv
        - Zensus2022_Staatsangehoerigkeit-Gitter.csv
        - Zensus2022_Gebaeude_mit_Wohnraum_nach_Energietraeger_der_Heizung-Gitter.csv
        - Zensus2022_Energietraeger-Gitter.csv  # UTF-8 encoding issue
        - Zensus2022_Deutsche_Staatsangehoerige_ab18-Gitter.csv   # UTF-8 encoding issue
        - Zensus2022_Groesse_des_privaten_Haushalts-Gitter.csv
        - Zensus2022_Durchschn_Nettokaltmiete-Gitter.csv
        - Zensus2022_Gebaeude_mit_Wohnraum_nach_ueberwiegender_Heizungsart-Gitter.csv
        - Zensus2022_Geb_Gebaeudetyp_Groesse-Gitter.csv
        - Zensus2022_Leerstandsquote-Gitter.csv

    lod2:
      status: active
      url:
        - "https://geodaten.bayern.de/odd/a/lod2/citygml/meta/metalink/09780139.meta4"
      path:
        lod2: "{loader/path/base}/lod2/"
        gml: "{loader/path/processed}/lod2/"

    bkg:
      status: active
      path:
        base: "{loader/path/base}/bkg/"
        zip: "{loader/sources/bkg/path/base}/zip/"
        unzip: "{loader/sources/bkg/path/base}/unzip/"
        processed: "{loader/path/processed}/bkg/"
      prefix: bkg
      schema: opendata
      vg500:
        url: "https://daten.gdz.bkg.bund.de/produkte/vg/vg5000_1231/aktuell/vg5000_12-31.utm32s.gpkg.ebenen.zip"
        layer:
          - "vg5000_gem"
          - "vg5000_krs"
          - "vg5000_lan"
          - "vg5000_li"
          - "vg5000_rbz"
          - "vg5000_sta"
          - "vg5000_vwg"
      nuts:
        url: "https://daten.gdz.bkg.bund.de/produkte/vg/nuts250_1231/aktuell/nuts250_12-31.utm32s.gpkg.zip"
        layer:
          - "nuts250_n1"
          - "nuts250_n2"
          - "nuts250_n3"
      geogitter:
        resolutions:
          - 100m
          - 1km
          - 10km

    basemap:
      status: active
      url: "https://basemap.de/dienste/opendata/basisviews/"
      ending: ".gpkg"
      filter:
        - by
      path:
        base: "{loader/path/base}/basemap/"
        processed: "{loader/path/processed}/basemap/"
      schema: opendata
      prefix: bmp
      layer:
        - barrierenlinie
        - bauwerksflaeche
        - bauwerkslinie
        - bauwerkspunkt
        - besondere_flaeche
        - besondere_linie
        - besonderer_punkt
        - gewaesserflaeche
        - gewaesserlinie
        - gewaesserpunkt
        - grenze_flaeche
        - grenze_linie
        - grenze_punkt
        - historische_flaeche
        - historische_linie
        - historischer_punkt
        - name_flaeche
        - name_punkt
        - reliefflaeche
        - relieflinie
        - reliefpunkt
        - siedlungsflaeche
        - vegetationsflaeche
        - vegetationslinie
        - vegetationspunkt
        - verkehrsflaeche
        - verkehrslinie
        - verkehrspunkt
        - versorgungslinie
        - versorgungspunkt
        - weitere_nutzung_flaeche

    plz:
      status: active
      url: "https://downloads.suche-postleitzahl.org/v2/public/plz-5stellig.geojson"
      path:
        base: "{loader/path/base}/plz/"
        processed: "{loader/path/processed}/plz/"
      schema: opendata
      prefix: plz
      layer:
        - plz-5stellig
