base:
  name: infdb-munich
  path:
    base: "../infdb-data/"
  network_name: infdb_network
  #base_sunset_dir: "{base/path/base}/sunset/"
services:
  citydb:
    user: citydb_user
    password: citydb_password
    db: citydb
    host: citydb
    exposed_port: 5433
    epsg: 25832 # 3035 (Europe)
    path: "{base/path/base}/{base/name}/citydb/"
    status: active
    compose_file: "dockers/citydb.yml"

  timescaledb:
    user: timescaledb_user
    password: timescaledb_password
    db: timescaledb
    host: timescaledb
    exposed_port: 5432
    status: active
    path: "{base/path/base}/{base/name}/timescaledb/"
    compose_file: "dockers/timescaledb.yml"

  pgadmin:
    default_email: admin@admin.com
    default_password: admin
    exposed_port: 81
    status: active
    compose_file: "dockers/pgadmin.yml"

  jupyter:
    exposed_port: 8888
    enable_lab: yes
    status: not-active
    volume_dir: "{base/path/base}/{base/name}/notebooks/"
    compose_file: "dockers/juypter.yml"

  qwc:
    exposed_port_gui: 80
    exposed_port_db: 5435
    postgres_password: qwc_password
    status: active
    compose_file: "dockers/qgis_webclient/docker-compose.yml"

configs:
  - config-services.yml