general:
  name: sonthofen
  base_dir: data/{{ general.name }}
  scope: DE27E
  schema: general

citydb:
  user: citydb_user
  password: citydb_password
  db: citydb
  host: 127.0.0.1
  host_container: citydb
  port: 5433
  epsg: "25832"
  srid: 4326
  db_dir: "{{ general.base_dir }}"
  status: active

citydbv4:
  user: citydb_user
  password: citydb_password
  db: citydb
  host: 127.0.0.1
  host_container: citydbv4
  port: 5434
  epsg: "25832"
  srid: 4326
  db_dir: "{{ general.base_dir }}"
  status: not-active

timescaledb:
  user: timescale_user
  password: secret
  db: timescaledb_db
  host: 127.0.0.1 
  port: 5432
  status: active

pgadmin:
  default_email: admin@admin.com
  default_password: admin
  port: 8080
  status: active


jupyter:
  status: not-active

opendata:
  opendata_dir: '{{ general.base_dir }}/opendata'
  zensus_2022:
    status: not-active
    resolutions:
      - 100m
    zensus_2022_dir: "{{ opendata.opendata_dir }}/zensus_2022"
    zensus_2022_zip_dir: "{{ opendata.zensus_2022.zensus_2022_dir }}/zip/"
    zensus_2022_unzip_dir: "{{ opendata.zensus_2022.zensus_2022_dir }}/unzip/"
    zensus_2022_processed_dir: "{{ opendata.zensus_2022.zensus_2022_dir }}/processed/"
    url: "https://www.zensus2022.de/DE/Ergebnisse-des-Zensus/_inhalt.html"
    schema: census2022

  lod2:
    status: not-active
    url:
      - "https://geodaten.bayern.de/odd/a/lod2/citygml/meta/metalink/09780139.meta4"
    lod2_dir: "{{ opendata.opendata_dir }}/lod2"
    gml_dir: "{{ opendata.lod2.lod2_dir }}/gml/"

  bkg:
    status: not-active
    bkg_dir: "{{ opendata.opendata_dir }}/bkg/"
    bkg_zip_dir: "{{ opendata.bkg.bkg_dir }}/zip/"
    bkg_unzip_dir: "{{ opendata.bkg.bkg_dir }}/unzip"
    bkg_processed_dir: "{{ opendata.bkg.bkg_dir }}/processed/"
    schema: bkg

  basemap:
    status: not-active
    url: "https://basemap.de/dienste/opendata/basisviews/"
    ending: ".gpkg"
    filter:
      - by
    basemap_dir: "{{ opendata.opendata_dir }}/basemap"
    basemap_processed_dir: "{{ opendata.basemap.basemap_dir }}/processed/"
    schema: basemap

  plz:
    status: not-active
    url: "https://downloads.suche-postleitzahl.org/v2/public/plz-5stellig.geojson"
    plz_dir: "{{ opendata.opendata_dir }}/plz"
    plz_processed_dir: "{{ opendata.basemap.basemap_dir }}/processed/"
    schema: plz
