# Configuration for the INFDB database setup
# Relative paths are relative to the project directory

base:
    name: infdb-munich
    path:
        base: "data-infdb/"
    network_name: infdb_network
services:
    citydb:
        user: citydb_user
        password: V#3rn+nmma!-c_9upZkM
        db: citydb
        host: citydb
        exposed_port: 54321
        epsg: 25832 # 3035 (Europe)
        path: 
            base: "{base/path/base}/{base/name}/citydb/"
            compose_file: "dockers/citydb.yml"
        status: active

    timescaledb:
        user: timescaledb_user
        password: V#3rn+nmma!-c_9upZkM
        db: timescaledb
        host: timescaledb
        exposed_port: 54331
        status: active
        path: 
            base: "{base/path/base}/{base/name}/timescaledb/"
            compose_file: "dockers/timescaledb.yml"

    pgadmin:
        default_email: admin@admin.com
        default_password: V#3rn+nmma!-c_9upZkM
        exposed_port: 811
        status: active
        path:
            compose_file: "dockers/pgadmin.yml"

    jupyter:
        exposed_port: 88881
        enable_lab: yes
        status: not-active
        path:
            base: "{base/path/base}/{base/name}/notebooks/"
            compose_file: "dockers/juypter.yml"

    qwc:
        status: active
        exposed_port_gui: 801
        exposed_port_db: 54341
        postgres_password: V#3rn+nmma!-c_9upZkM
        path:
            compose_file: "dockers/qgis_webclient/docker-compose.yml"
