services:
  citydb:
    user: citydb_user
    password: citydb_password
    db: citydb
    host: citydb
    exposed_port: 5433
    epsg: 25832 # 3035 (Europe)
    path: "{base/path/base}/{base/name}/citydb/"
    status: active
    compose_file: "dockers/services/citydb.yml"

  timescaledb:
    user: timescale_user
    password: secret
    db: timescaledb_db
    host: timescaledb
    exposed_port: 5432
    status: active
    path: "{base/path/base}/{base/name}/timescaledb/"
    compose_file: "dockers/services/timescaledb.yml"

  pgadmin:
    default_email: admin@admin.com
    default_password: admin
    exposed_port: 81
    status: active
    compose_file: "dockers/services/pgadmin.yml"

  jupyter:
    exposed_port: 8888
    enable_lab: yes
    status: not-active
    volume_dir: "{base/path/base}/{base/name}/notebooks/"
    compose_file: "dockers/services/juypter.yml"

  qwc:
    exposed_port: 80
    status: not-active
    compose_file: "dockers/services/juypter.yml"

