# Configuration for the INFDB database setup
# Relative paths are relative to the project directory

base:
    name: infdb-munich
    path:
        base: "data-infdb/"
    network_name: infdb_network
services:
    citydb:
        user: citydb_user
        password: infdb
        db: citydb
        host: citydb
        exposed_port: 5432
        epsg: 25832 # 3035 (Europe)
        path: 
            base: "{base/path/base}/{base/name}/citydb/"
            compose_file: "services/3dcitydb/compose.yml"
        status: active

    timescaledb:
        user: timescaledb_user
        password: infdb
        db: timescaledb
        host: timescaledb
        exposed_port: 5433
        status: active
        path: 
            base: "{base/path/base}/{base/name}/timescaledb/"
            compose_file: "services/timescaledb/compose.yml"

    pgadmin:
        default_email: admin@admin.com
        default_password: infdb
        exposed_port: 81
        status: active
        path:
            compose_file: "services/pgadmin/compose.yml"

    jupyter:
        exposed_port: 8888
        enable_lab: yes
        status: not-active
        path:
            base: "{base/path/base}/{base/name}/notebooks/"
            compose_file: "services/juypter/compose.yml"

    qwc:
        status: active
        exposed_port_gui: 80
        exposed_port_db: 5434
        postgres_password: infdb
        path:
            compose_file: "services/qgis_webclient/docker-compose.yml"
