base:
  name: bergkirchen
  path:
    base: "infdb-data/"
  scope: 09174113 #ags
  schema: general
  network_name: network
  environment: container
  base_sunset_dir: "{base/path/base}/sunset/"

configs:
  - config-loader.yml
  - config-services.yml
  - config-processor.yml