base:
  name: sonthofen
  base_dir: "data/{name}/"
  scope: DE27E
  schema: general
  network_external_name: infdb_external_network
  network_internal_name: infdb_internal_network
  environment: container