base:
  name: sonthofen
  base_dir: "data/{name}/"
  scope: DE27E
  schema: general
  network_name: network
  environment: container
  base_sunset_dir: "{base_dir}/sunset/"

configs:
  - config-loader.yml
  - config-services.yml