services:
  citydb:
    user: citydb_user
    password: citydb_password
    db: citydb
    host: citydb
    port: 5432
    exposed_port: 5433
    epsg: 25832
    db_dir: "{base_dir}/3dcdb/"
    status: active

  timescaledb:
    user: timescale_user
    password: secret
    db: timescaledb_db
    host: timescaledb
    port: 5432
    exposed_port: 5432
    status: active

  pgadmin:
    default_email: admin@admin.com
    default_password: admin
    port: 80
    exposed_port: 81
    status: active

  jupyter:
    port: 8888
    exposed_port: 8888
    enable_lab: yes
    status: active

