loader:
  loader_dir: "{base_dir}/opendata"
  zensus_2022:
    status: not-active
    resolutions:
      - 100m
    zensus_2022_dir: "{loader_dir}/zensus_2022/"
    zensus_2022_zip_dir: "{zensus_2022_dir}/zip/"
    zensus_2022_unzip_dir: "{zensus_2022_dir}/unzip/"
    zensus_2022_processed_dir: "{zensus_2022_dir}/processed/"
    url: "https://www.zensus2022.de/DE/Ergebnisse-des-Zensus/_inhalt.html"
    schema: census2022

  lod2:
    status: active
    url:
      - "https://geodaten.bayern.de/odd/a/lod2/citygml/meta/metalink/09780139.meta4"
    lod2_dir: "{loader_dir}/lod2/"
    gml_dir: "{lod2_dir}/gml/"

  bkg:
    status: active
    bkg_dir: "{loader_dir}/bkg/"
    bkg_zip_dir: "{bkg_dir}/zip/"
    bkg_unzip_dir: "{bkg_dir}/unzip/"
    bkg_processed_dir: "{bkg_dir}/processed/"
    schema: bkg

  basemap:
    status: not-active
    url: "https://basemap.de/dienste/opendata/basisviews/"
    ending: ".gpkg"
    filter:
      - by
    basemap_dir: "{loader_dir}/basemap/"
    basemap_processed_dir: "{basemap_dir}/processed/"
    schema: basemap

  plz:
    status: not-active
    url: "https://downloads.suche-postleitzahl.org/v2/public/plz-5stellig.geojson"
    plz_dir: "{loader_dir}/plz/"
    plz_processed_dir: "{basemap_dir}/processed/"
    schema: plz
