services:
  citydb-tool:
    image: 3dcitydb/citydb-tool
    #container_name: citydb-tool
    environment:
      CITYDB_HOST: citydb
      CITYDB_PORT: 5432
      CITYDB_NAME: ${CITYDB_DB}
      CITYDB_USERNAME: ${CITYDB_USER}
      CITYDB_PASSWORD: ${CITYDB_PASSWORD}
      SRID: ${CITYDB_EPSG}
    command: import citygml /data/
    volumes:
      - ../../${GML_DIR}/:/data/
    networks:
      - ${NETWORK_NAME}
    depends_on:
        loader:
            condition: service_completed_successfully
