services:
  citydb-tool:
    image: 3dcitydb/citydb-tool
    #container_name: citydb-tool
    environment:
      CITYDB_HOST: ${LOADER_HOSTS_CITYDB_HOST}
      CITYDB_PORT: ${LOADER_HOSTS_CITYDB_PORT}
      CITYDB_NAME: ${SERVICES_CITYDB_DB}
      CITYDB_USERNAME: ${LOADER_HOSTS_CITYDB_USER}
      CITYDB_PASSWORD: ${LOADER_HOSTS_CITYDB_PASSWORD}
      SRID: ${LOADER_HOSTS_CITYDB_EPSG}
    command: import citygml /data/
    volumes:
      - ../../${LOADER_SOURCES_LOD2_PATH_GML}/:/data/
    depends_on:
      loader:
        condition: service_completed_successfully
networks:
  infdb:
    external: true
    name: infdb_${BASE_NETWORK_NAME}
