services:
  loader:
    build:
      context: ../..
      dockerfile: src/services/loader/Dockerfile
    container_name: loader
    networks:
      - infdb
    volumes:
      - ../../configs:/app/configs
      - ../../${LOADER_PATH_BASE}:/app/${LOADER_PATH_BASE}/
networks:
  infdb:
    external: true
    name: infdb_${BASE_NETWORK_NAME}