services:
    infdb-basedata-ways:
        profiles: [ "linear", "pylovo","basedata-ways"]
        image: infdb/basedata-ways:latest
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            # - ./configs:/workspaces/infdb-basedata-ways/configs:ro  # for production
            - .:/workspaces/infdb-basedata-ways # for development only
            - ../../src/infdb_package:/workspaces/infdb_package
            # - /workspaces/infdb-basedata-ways/.venv # Exclude .venv from volume mount
            - .vscode:/workspaces/.vscode:ro
        extra_hosts:
            - "host.docker.internal:host-gateway"
        env_file:
            - ../../.env          # root env (DB creds, CONFIG_INFDB_PATH, etc.)
            - env_infdb_basedata_ways.env
        environment:
            - UV_LINK_MODE=copy
        depends_on:
            infdb-basedata-buildings:
                condition: service_completed_successfully
