name: Publish qwc-qgis-server docker image

on: [push]

jobs:

    build:
      runs-on: ubuntu-latest
      steps:

      - uses: actions/checkout@master

      - name: Get version tag
        id: get_tag
        run: |
          if [ ${{ startsWith(github.ref, 'refs/tags/') }} = true ]; then
            echo ::set-output name=tag::${GITHUB_REF:10}
          else
            echo ::set-output name=tag::
          fi

      - name: Build and publish docker image
        uses: elgohr/Publish-Docker-Github-Action@2.12
        env:
          URL_PREFIX: /ows
        with:
          name: sourcepole/qwc-qgis-server
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          tags: "latest,${{ steps.get_tag.outputs.tag }}"
          workdir: qgis-server
          buildargs: URL_PREFIX
